version: '3'

services: 
  base:
    build: .
    volumes: 
      - .:/www
  web:
    extends:
      service: base
    hostname: web
    ports: 
      - "5000:5000"
    links: 
      - db
      - redis
    
  db:
    image: mysql:5.7
    hostname: db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: insta_admin
      MYSQL_PASSWORD: insta2018
      MYSQL_DATABASE: insta_db
    volumes:
      - sample_volume:/var/lib/mysql 
      
  redis:
    image: redis:latest
    hostname: redis

  celery-worker:
    extends:
      service: base
    environment: 
      - C_FORCE_ROOT=true
    command: "celery worker -A celery_worker.celery --loglevel=info"
    deploy:
      replicas: 5
    links:
      - redis
    depends_on: 
      - redis
      - celery-beat  
  
  celery-beat:
    extends:
      service: base
    environment: 
      - C_FORCE_ROOT=true
    command: "celery -A celery_worker.celery beat --loglevel=info"  
    links:
      - redis  

volumes:
  sample_volume:      